<a href="https://colab.research.google.com/github/Shrutik4929/Quickcommerce_project/blob/main/quick_commerce.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/quick_commerce_data_raw.csv")

In [ ]:
df.head()

,Order_ID,Company,City,Customer_Age,Order_Value,Delivery_Time_Min,Distance_Km,Items_Count,Product_Category,Payment_Method,Customer_Rating,Discount_Applied,Delivery_Partner_Rating
0,1000001,Swiggy Instamart,Noida,46.0,702.33750,19.182,11.97,12.0,Dairy,Wallet,2.1,1.0,3.2
1,1000002,Flipkart Minutes,Amritsar,56.0,1007.30000,19.644,12.74,10.0,Snacks,Cash on Delivery,2.3,0.0,3.2
2,1000003,Flipkart Minutes,Mumbai,18.0,1211.66000,16.910,4.85,NaN,Personal Care,Cash on Delivery,3.3,0.0,3.8
3,1000004,Swiggy Instamart,Delhi,23.0,1179.05925,5.864,6.44,2.0,Dairy,Credit Card,5.0,1.0,5.0
4,1000005,Dunzo,Mumbai,44.0,586.02550,12.470,2.45,13.0,Household,Wallet,3.7,0.0,4.8

In [ ]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 228650 entries, 0 to 228649
Data columns (total 13 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Order_ID                 228650 non-null  int64
 1   Company                  228649 non-null  object
 2   City                     216845 non-null  object
 3   Customer_Age             228649 non-null  float64
 4   Order_Value              228649 non-null  float64
 5   Delivery_Time_Min        228649 non-null  float64
 6   Distance_Km              228649 non-null  float64
 7   Items_Count              220704 non-null  float64
 8   Product_Category         228649 non-null  object
 9   Payment_Method           228649 non-null  object
 10  Customer_Rating          217959 non-null  float64
 11  Discount_Applied         228649 non-null  float64
 12  Delivery_Partner_Rating  204799 non-null  float64
dtypes: float64(8), int64(1), object(4)
memory usage: 22.7+ MB

,Order_ID,Customer_Age,Order_Value,Delivery_Time_Min,Distance_Km,Items_Count,Customer_Rating,Discount_Applied,Delivery_Partner_Rating
count,2.286500e+05,228649.000000,228649.000000,228649.000000,228649.000000,220704.000000,217959.000000,228649.00000,204799.000000
mean,1.114320e+06,38.458441,571.507051,16.469592,7.763030,9.994196,3.042631,0.40274,3.748337
std,6.604632e+04,12.123389,381.816694,6.279282,4.187772,5.475455,1.187207,0.49045,0.721395
min,1.228000e+03,18.000000,50.000000,5.000000,0.500000,1.000000,1.000000,0.00000,2.500000
25%,1.057162e+06,28.000000,287.530000,12.366000,4.140000,5.000000,2.000000,0.00000,3.100000
50%,1.114324e+06,38.000000,532.459800,16.346000,7.770000,10.000000,3.000000,0.00000,3.700000
75%,1.171487e+06,49.000000,795.901500,20.216000,11.400000,15.000000,4.000000,1.00000,4.400000
max,1.228649e+06,59.000000,13180.905000,39.994000,15.000000,19.000000,5.000000,1.00000,5.000000

In [ ]:
print("Duplicate Rows:", df.duplicated().sum())

Duplicate Rows: 0

In [ ]:
df.isnull().sum()

Order_ID                       0
Company                        1
City                       11805
Customer_Age                   1
Order_Value                    1
Delivery_Time_Min              1
Distance_Km                    1
Items_Count                 7946
Product_Category               1
Payment_Method                 1
Customer_Rating            10691
Discount_Applied               1
Delivery_Partner_Rating    23851
dtype: int64

In [ ]:
df['Items_Count'] = df['Items_Count'].fillna(df['Items_Count'].median())

In [ ]:
df['Items_Count'] = df['Items_Count'].astype(int)

In [ ]:
df['Customer_Rating'] = df['Customer_Rating'].fillna(df['Customer_Rating'].median())

In [ ]:
df['Discount_Applied'] = df['Discount_Applied'].fillna(0)
df['Discount_Applied'] = df['Discount_Applied'].astype(int)

In [ ]:
df['Delivery_Partner_Rating'] = df['Delivery_Partner_Rating'].fillna(df['Delivery_Partner_Rating'].median())

In [ ]:
df.isnull().sum()

Order_ID                   0
Company                    0
City                       0
Customer_Age               0
Order_Value                0
Delivery_Time_Min          0
Distance_Km                0
Items_Count                0
Product_Category           0
Payment_Method             0
Customer_Rating            0
Discount_Applied           0
Delivery_Partner_Rating    0
dtype: int64

In [ ]:

df.dropna(subset=['City'], inplace=True)

print(df.isnull().sum())

Order_ID                   0
Company                    0
City                       0
Customer_Age               0
Order_Value                0
Delivery_Time_Min          0
Distance_Km                0
Items_Count                0
Product_Category           0
Payment_Method             0
Customer_Rating            0
Discount_Applied           0
Delivery_Partner_Rating    0
dtype: int64

In [ ]:
df.dtypes

Order_ID                     int64
Company                     object
City                        object
Customer_Age               float64
Order_Value                float64
Delivery_Time_Min          float64
Distance_Km                float64
Items_Count                  int64
Product_Category            object
Payment_Method              object
Customer_Rating            float64
Discount_Applied             int64
Delivery_Partner_Rating    float64
dtype: object

In [ ]:
df['Order_Value'] = df['Order_Value'].round(2)

In [ ]:
df['Order_Value']

0          702.34
1         1007.30
2         1211.66
3         1179.06
4          586.03
           ...
228644      50.00
228645     465.44
228646     266.73
228647     277.08
228648     338.57
Name: Order_Value, Length: 216845, dtype: float64

In [ ]:
df['Delivery_Time_Min']

0         19.182
1         19.644
2         16.910
3          5.864
4         12.470
           ...
228644    23.752
228645    14.966
228646    18.576
228647    13.844
228648    12.034
Name: Delivery_Time_Min, Length: 216845, dtype: float64

In [ ]:
df['Delivery_Time_Min'] = df['Delivery_Time_Min'].round()

In [ ]:
df['Delivery_Time_Min'] = df['Delivery_Time_Min'].astype(int)

In [ ]:
df['Delivery_Time_Min']

0         19
1         20
2         17
3          6
4         12
          ..
228644    24
228645    15
228646    19
228647    14
228648    12
Name: Delivery_Time_Min, Length: 216845, dtype: int64

In [ ]:
df['Customer_Rating'] = df['Customer_Rating'].round(2)

In [ ]:
df['Customer_Rating']

0         2.1
1         2.3
2         3.3
3         5.0
4         3.7
         ...
228644    2.8
228645    1.4
228646    1.2
228647    4.7
228648    4.2
Name: Customer_Rating, Length: 216845, dtype: float64

In [ ]:
df['Discount_Applied'].unique()

array([1, 0])

In [ ]:
df.head()

,Order_ID,Company,City,Customer_Age,Order_Value,Delivery_Time_Min,Distance_Km,Items_Count,Product_Category,Payment_Method,Customer_Rating,Discount_Applied,Delivery_Partner_Rating
0,1000001,Swiggy Instamart,Noida,46.0,702.34,19,11.97,12,Dairy,Wallet,2.1,1,3.2
1,1000002,Flipkart Minutes,Amritsar,56.0,1007.30,20,12.74,10,Snacks,Cash on Delivery,2.3,0,3.2
2,1000003,Flipkart Minutes,Mumbai,18.0,1211.66,17,4.85,10,Personal Care,Cash on Delivery,3.3,0,3.8
3,1000004,Swiggy Instamart,Delhi,23.0,1179.06,6,6.44,2,Dairy,Credit Card,5.0,1,5.0
4,1000005,Dunzo,Mumbai,44.0,586.03,12,2.45,13,Household,Wallet,3.7,0,4.8

In [ ]:
df.tail()

,Order_ID,Company,City,Customer_Age,Order_Value,Delivery_Time_Min,Distance_Km,Items_Count,Product_Category,Payment_Method,Customer_Rating,Discount_Applied,Delivery_Partner_Rating
228644,1228645,Dunzo,Haridwar,56.0,50.00,24,7.92,17,Snacks,Cash on Delivery,2.8,0,3.4
228645,1228646,Flipkart Minutes,Hyderabad,27.0,465.44,15,6.61,3,Dairy,UPI,1.4,1,3.9
228646,1228647,Dunzo,Jaipur,44.0,266.73,19,10.96,3,Household,UPI,1.2,0,4.4
228647,1228648,Blinkit,Pune,54.0,277.08,14,9.74,7,Dairy,Credit Card,4.7,0,3.6
228648,1228649,Flipkart Minutes,Hyderabad,48.0,338.57,12,3.39,16,Beverages,Debit Card,4.2,0,2.9

In [ ]:
df['Age_Group'] = pd.cut(df['Customer_Age'],
    bins=[17, 25, 35, 50, 100],
    labels=['Young Adult', 'Adult', 'Middle Age', 'Senior'])

In [ ]:
df[['Customer_Age','Age_Group']]

        Customer_Age    Age_Group
0               46.0   Middle Age
1               56.0       Senior
2               18.0  Young Adult
3               23.0  Young Adult
4               44.0   Middle Age
...              ...          ...
228644          56.0       Senior
228645          27.0        Adult
228646          44.0   Middle Age
228647          54.0       Senior
228648          48.0   Middle Age

[216845 rows x 2 columns]

In [ ]:
df.columns

Index(['Order_ID', 'Company', 'City', 'Customer_Age', 'Order_Value',
       'Delivery_Time_Min', 'Distance_Km', 'Items_Count', 'Product_Category',
       'Payment_Method', 'Customer_Rating', 'Discount_Applied',
       'Delivery_Partner_Rating', 'Age_Group'],
      dtype='object')

In [ ]:
df.to_csv("quick_commerce_data_final.csv", index=False)